
package es.uam.eps.bmi.search.indexing.stemmer;

 /**
  * This class was automatically generated by a Snowball to Java compiler 
  * It implements the stemming algorithm defined by a snowball script.
  */

public abstract class SnowballStemmer extends SnowballProgram {
    public abstract boolean stem();
};
